using UnityEngine;
using Photon.Pun;
using Photon.Realtime;
using ExitGames.Client.Photon;
using System.Collections.Generic;
using System.Linq;

public enum PlacementRule { LandOnly, WaterOnly, Pier }

public class BuildingManager : MonoBehaviour, IOnEventCallback
{
    public static BuildingManager Instance;
    private static HashSet<Vector2> occupiedBuildingCells = new HashSet<Vector2>();

    public static bool IsOccupied(Vector2 pos)
    {
        return occupiedBuildingCells.Contains(new Vector2(Mathf.Round(pos.x), Mathf.Round(pos.y)));
    }

    public static void RegisterOccupancy(Vector2 center, int width, int height)
    {
        float startX = -(width - 1) / 2f;
        float startY = -(height - 1) / 2f;
        for (int x = 0; x < width; x++)
        {
            for (int y = 0; y < height; y++)
            {
                occupiedBuildingCells.Add(center + new Vector2(startX + x, startY + y));
            }
        }
    }

    [Header("Building Prefabs")]
    [SerializeField] private Material warehouseMaterial;
    [Header("Steg Prefab")]
    public GameObject stegPrefab;

    // aktive Stege
    private static HashSet<Steg> stegs = new HashSet<Steg>();

    private void Awake()
    {
        if (Instance == null) Instance = this;
        else Destroy(gameObject);

        occupiedBuildingCells.Clear();
    }

    // --- Steg-Management (1x1 Stege im Wasser) ---
    public static void RegisterSteg(Steg s) => stegs.Add(s);
    public static void UnregisterSteg(Steg s) => stegs.Remove(s);

    // Platzieren eines Stegs an einer World-Position (X,Y). Gibt true zurück, wenn platziert.
    public bool PlaceStegAt(Vector2 position, bool isLocal = true)
    {
        if (stegPrefab == null) { Debug.LogWarning("BuildingManager: stegPrefab fehlt"); return false; }

        Vector2Int grid = new Vector2Int(Mathf.RoundToInt(position.x), Mathf.RoundToInt(position.y));
        if (!IsWaterAt(grid)) return false;
        if (!HasAdjacency(grid)) return false;

        GameObject go = Instantiate(stegPrefab);
        var steg = go.GetComponent<Steg>();
        if (steg == null) { Debug.LogError("stegPrefab hat keine Steg-Komponente"); Destroy(go); return false; }
        steg.Initialize(new Vector3(position.x, position.y, -0.21f));

        RegisterOccupancy(position, 1, 1);
        return true;
    }

    public static void OnStegRemoved(Steg removed)
    {
        UnregisterSteg(removed);
        if (Instance != null) Instance.ReevaluateSupports();
    }

    void ReevaluateSupports()
    {
        var all = stegs.ToList();
        HashSet<Steg> supported = new HashSet<Steg>();

        foreach (var s in all)
        {
            if (IsAdjacentToLand(s.GridPosition)) supported.Add(s);
        }

        Queue<Steg> q = new Queue<Steg>(supported);
        while (q.Count > 0)
        {
            var cur = q.Dequeue();
            foreach (var n in GetStegNeighbors(cur))
            {
                if (!supported.Contains(n)) { supported.Add(n); q.Enqueue(n); }
            }
        }

        foreach (var s in all)
        {
            if (!supported.Contains(s))
            {
                stegs.Remove(s);
                if (s != null) Destroy(s.gameObject);
            }
        }
    }

    static bool IsWaterAt(Vector2Int grid)
    {
        // The world is generated by IslandManager: cells present in IslandManager are land,
        // everything else is water. Use that logical map instead of tags.
        Vector2 v = new Vector2(grid.x, grid.y);
        return !IslandManager.IsLand(v);
    }

    bool HasAdjacency(Vector2Int grid)
    {
        Vector2Int[] dirs = { new Vector2Int(1, 0), new Vector2Int(-1, 0), new Vector2Int(0, 1), new Vector2Int(0, -1) };
        foreach (var d in dirs)
        {
            Vector2Int n = grid + d;
            // Adjacent to generated land?
            if (IslandManager.IsLand(new Vector2(n.x, n.y))) return true;
            // Or adjacent to an existing steg?
            if (stegs.Any(s => s.GridPosition == n)) return true;
        }
        return false;
    }

    static bool IsAdjacentToLand(Vector2Int grid)
    {
        Vector2Int[] dirs = { new Vector2Int(1, 0), new Vector2Int(-1, 0), new Vector2Int(0, 1), new Vector2Int(0, -1) };
        foreach (var d in dirs)
        {
            Vector2Int n = grid + d;
            if (IslandManager.IsLand(new Vector2(n.x, n.y))) return true;
        }
        return false;
    }

    IEnumerable<Steg> GetStegNeighbors(Steg s)
    {
        Vector2Int[] dirs = { new Vector2Int(1, 0), new Vector2Int(-1, 0), new Vector2Int(0, 1), new Vector2Int(0, -1) };
        foreach (var d in dirs)
        {
            Vector2Int n = s.GridPosition + d;
            foreach (var other in stegs)
            {
                if (other.GridPosition == n) yield return other;
            }
        }
    }

    private void OnEnable()
    {
        PhotonNetwork.AddCallbackTarget(this);
    }

    private void OnDisable()
    {
        PhotonNetwork.RemoveCallbackTarget(this);
    }

    public void OnEvent(EventData photonEvent)
    {
        if (photonEvent.Code == 2)
        {
            object[] data = (object[])photonEvent.CustomData;
            string buildingName = (string)data[0];
            Vector2 pos = (Vector2)data[1];

            BuildingData bData = GetBuildingDataByName(buildingName);
            if (bData != null)
            {
                SpawnBuilding(bData, pos, false);
            }
        }
    }

    private BuildingData GetBuildingDataByName(string name)
    {
        BuildingData[] allData = Resources.FindObjectsOfTypeAll<BuildingData>();
        foreach (var d in allData)
        {
            if (d.buildingName == name) return d;
        }
        return null;
    }

    public void SpawnBuilding(BuildingData data, Vector2 position, bool isLocal = true)
    {
        if (data.prefab == null) return;

        GameObject building = Instantiate(data.prefab, new Vector3(position.x, position.y, -0.21f), Quaternion.identity);
        building.name = data.buildingName;

        // Scale the visual so the texture covers exactly the building's grid footprint.
        // We measure the natural rendered size first (independent of any prefab scale),
        // then compute a factor so the result is exactly data.width × data.height world units.
        building.transform.localScale = Vector3.one; // reset before measuring

        float naturalW = 1f, naturalH = 1f;

        SpriteRenderer buildingSR = building.GetComponentInChildren<SpriteRenderer>();
        if (buildingSR != null && buildingSR.sprite != null)
        {
            // sprite.bounds is in local space at scale 1 – exactly what we need
            naturalW = buildingSR.sprite.bounds.size.x;
            naturalH = buildingSR.sprite.bounds.size.y;
        }
        else
        {
            Renderer buildingRend = building.GetComponentInChildren<Renderer>();
            if (buildingRend != null)
            {
                // bounds at scale (1,1,1) gives the natural world-unit size
                naturalW = buildingRend.bounds.size.x;
                naturalH = buildingRend.bounds.size.y;
            }
        }

        if (naturalW <= 0f) naturalW = 1f;
        if (naturalH <= 0f) naturalH = 1f;

        building.transform.localScale = new Vector3(
            data.width  / naturalW,
            data.height / naturalH,
            1f
        );

        // Add building instance logic
        BuildingInstance instance = building.AddComponent<BuildingInstance>();
        instance.data = data;
        instance.isLocal = isLocal;

        FogRevealer revealer = building.GetComponent<FogRevealer>();
        if (revealer == null) revealer = building.AddComponent<FogRevealer>();
        revealer.isLocalPlayer = isLocal;
        // Use custom reveal radius for certain buildings (e.g. towers, warehouses)
        if (data != null && data.revealRadius > 0f)
        {
            revealer.radius = data.revealRadius;
        }

        // If this building is a defensive tower, attach tower behaviour
        if (data != null && data.isDefenseTower)
        {
            ArcherTower tower = building.AddComponent<ArcherTower>();
            tower.slots = Mathf.Max(0, data.archerSlots);
            tower.range = data.towerRange > 0f ? data.towerRange : tower.range;
            tower.damage = data.towerDamage > 0f ? data.towerDamage : tower.damage;
            tower.cooldown = data.towerCooldown > 0f ? data.towerCooldown : tower.cooldown;
            tower.team = isLocal ? Team.Player : Team.Enemy;
        }

        // Apply red tint to enemy buildings
        if (!isLocal)
        {
            foreach (Renderer r in building.GetComponentsInChildren<Renderer>())
            {
                if (r.gameObject.name != "FogMask") // Don't tint the fog mask
                    r.material.color = new Color(1f, 0.5f, 0.5f, 1f);
            }
        }

        RegisterOccupancy(position, data.width, data.height);
    }

    public void SpawnMainWarehouse(Vector2 position, bool isLocal = true)
    {
        GameObject warehouse = GameObject.CreatePrimitive(PrimitiveType.Quad);
        warehouse.name = isLocal ? "MyWarehouse" : "EnemyWarehouse";
        warehouse.transform.position = new Vector3(position.x, position.y, -0.21f);
        warehouse.transform.localScale = new Vector3(3f, 3f, 1f); 

        FogRevealer revealer = warehouse.AddComponent<FogRevealer>();
        revealer.radius = 10f;
        revealer.isLocalPlayer = isLocal;

        Renderer rend = warehouse.GetComponent<Renderer>();

        if (warehouseMaterial != null)
        {
            rend.material = new Material(warehouseMaterial);
        }
        else
        {
            Shader warehouseShader = Shader.Find("Unlit/Transparent") ?? Shader.Find("Sprites/Default") ?? Shader.Find("Standard");
            if (warehouseShader == null)
            {
                Debug.LogWarning("[BuildingManager] Keine Warehouse-Shader gefunden. Verwende Standardmaterial.");
                rend.material = new Material(Shader.Find("Sprites/Default"));
            }
            else
            {
                rend.material = new Material(warehouseShader);
            }
        }

        Texture2D tex = Resources.Load<Texture2D>("warehouse_texture");
        if (tex == null)
        {
            tex = Resources.Load<Texture2D>("Textures/warehouse_texture");
        }

        if (tex != null)
        {
            rend.material.mainTexture = tex;
        }
        else
        {
            Debug.LogWarning("[BuildingManager] warehouse_texture nicht gefunden. Verwende graues Ersatzmaterial.");
            rend.material.color = new Color(0.75f, 0.75f, 0.75f, 1f);
        }

        if (!isLocal)
        {
            Color enemyColor = new Color(1f, 0.5f, 0.5f, 1f);
            rend.material.color = enemyColor;
        }

        RegisterOccupancy(position, 3, 3);
        var meshCollider = warehouse.GetComponent<MeshCollider>();
        if (meshCollider != null)
        {
            DestroyImmediate(meshCollider);
        }

        BuildingInstance lodging = warehouse.AddComponent<BuildingInstance>();
        lodging.isLocal = isLocal;
        lodging.isPreBuiltLodging = true;
        lodging.displayNameOverride = "Hauptlager";
        lodging.sleepCapacityOverride = 5;
    }
}
